name: Trigger auto deployment for az104labcontainer02

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/az104labcontainer02-AutoDeployTrigger-e8162b6b-80f2-4cbf-9435-f8920bab1c2f.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZ104LABCONTAINER02_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZ104LABCONTAINER02_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZ104LABCONTAINER02_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: 
          registryUsername: ${{ secrets.AZ104LABCONTAINER02_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.AZ104LABCONTAINER02_REGISTRY_PASSWORD }}
          containerAppName: az104labcontainer02
          resourceGroup: AVNM_Managed_ResourceGroup_e4b3cd41-49b4-4e73-a572-fbeb16485031
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


